Controllers/SeedingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using web_dev_online_library.Models;

namespace web_dev_online_library.Controllers
{
    public class SeedingController : Controller
    {
        private readonly LibraryContext _context;

        public SeedingController(LibraryContext context)
        {
            _context = context;
        }

        public IActionResult ExtendDbWithDummies()
        {
	    using (var transaction = _context.Database.BeginTransaction())
            {
                try
                {
		    var newPerson1 = new Person { Name = "John", Surname = "Doe"};
		    var newPerson2 = new Person { Name = "Jane", Surname = "Doe" };
		    var newLibrarian = new Librarian { Person = newPerson1, EmploymentDate = DateTime.Today };
		    var newReader = new Reader { Person = newPerson2, RegistrationDate = DateTime.Today };
		    var newBorrow1 = new Borrow { BorrowDate = DateTime.Now, ReturnDate = null, Book = _context.Books.FirstOrDefault(b => b.Name == "Kateryna"), Librarian = newLibrarian, Reader = newReader };
		    var newBorrow2 = new Borrow { BorrowDate = DateTime.Now, ReturnDate = null, Book = _context.Books.FirstOrDefault(b => b.Name == "Hundred Thousand"), Librarian = _context.Librarians.FirstOrDefault(l => l.Person.Name == "Anna"), Reader = _context.Readers.FirstOrDefault(r => r.Person.Name == "Nikita") };

		    _context.People.Add(newPerson1);
		    _context.People.Add(newPerson2);
		    _context.Librarians.Add(newLibrarian);
		    _context.Readers.Add(newReader);
		    _context.Borrows.Add(newBorrow1);
		    _context.Borrows.Add(newBorrow2);

                    _context.SaveChanges();
                    transaction.Commit();
                }
                catch (Exception)
                {
                    transaction.Rollback();
                }
            }
            return RedirectToAction("Index", "Book");
        }

	public IActionResult FailExtendDbWithDummies()
	{
	    using (var transaction = _context.Database.BeginTransaction())
            {
                try
                {
		    var newPerson = new Person { Name = "J", Surname = "D"};
		    _context.People.Remove(_context.People.FirstOrDefault(p => p.Name == "J" && p.Surname == "D"));
		    var newBorrow = new Borrow { BorrowDate = DateTime.Now, ReturnDate = null, Book = _context.Books.FirstOrDefault(b => b.Name == "Hundred Thousand"), Librarian = _context.Librarians.FirstOrDefault(l => l.Person.Name == "J"), Reader = _context.Readers.FirstOrDefault(r => r.Person.Name == "J") };
		    var newLibrarian = new Librarian { Person = newPerson, EmploymentDate = DateTime.Today };
		    var newReader = new Reader { Person = newPerson, RegistrationDate = DateTime.Today };

		    _context.People.Add(newPerson);
		    _context.Librarians.Add(newLibrarian);
		    _context.Readers.Add(newReader);
		    _context.Borrows.Add(newBorrow);

                    _context.SaveChanges();
                    transaction.Commit();
                }
                catch (Exception)
                {
                    transaction.Rollback();
                }
            }
	    return RedirectToAction("Index", "Book");
	}
    }
}

Views/Shared/_Layout.cshtml
@{
	ViewData["NavbarItems"] = new Link[]
	{
		new Link("Books", "Book", "Index"),
		new Link("Genres", "Genre", "Index"),
		new Link("Librarians", "Librarian", "Index"),
		new Link("Readers", "Reader", "Index"),
		new Link("Writers", "Writer", "Index"),
		new Link("Publishers", "Publisher", "Index"),
		new Link("Borrows", "Borrow", "Index"),
		new Link("People", "Person", "Index")
	};
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - web_dev_online_library</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/web_dev_online_library.styles.css" asp-append-version="true" />
</head>
<body>
<header>
	<nav>
		<ul class="nav nav-tabs justify-content-center">
			@if (ViewData["NavbarItems"] is Link[] items)
			{
				foreach (var item in items)
				{
				    <li class="nav-item">
					<a
					    class="
					    nav-link 
					    text-dark 
					    @(item.Controller.Equals(ViewContext.RouteData.Values["controller"]?.ToString()) ? "active" : "")"
					    asp-area=""
					    asp-controller=@item.Controller
					    asp-action=@item.Action>
					    @item.Name
					</a>
				    </li>
				}
			}
			<li class="nav-item col"></li>
			<a asp-controller="Seeding" asp-action="ExtendDbWithDummies"><button type="button" class="btn btn-link">Extend Db Tables with Dummy Values</button></a>
			<!--<a asp-controller="Seeding" asp-action="FailExtendDbWithDummies"><button type="button" class="btn btn-link">Fail Extend Db Tables with Dummy Values</button></a>-->
		</ul>
	</nav>
</header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>